version: '3'
services:
  scrumpoker:
    image: scrumpoker
    ports:
      - 3000:3000
    environment:
      scrumpoker_connection_string: ${scrumpoker_connection_string}
#networks:
#  default:
#    external:
#      name: host